//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonstratureDB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseContext : DbContext
    {
        public DatabaseContext()
            : base("name=DemonstratureEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CourseT> CourseT { get; set; }
        public virtual DbSet<CourseUserT> CourseUserT { get; set; }
        public virtual DbSet<GroupT> GroupT { get; set; }
        public virtual DbSet<TermT> TermT { get; set; }
        public virtual DbSet<UserT> UserT { get; set; }
    }
}
