//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonstratureDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TermT
    {
        public int Id { get; set; }
        public int CourseId { get; set; }
        public Nullable<int> UserId { get; set; }
        public int GroupId { get; set; }
        public Nullable<System.DateTime> TermDate { get; set; }
        public Nullable<int> SuggestedUserId { get; set; }
    
        public virtual CourseT CourseT { get; set; }
        public virtual GroupT GroupT { get; set; }
        public virtual UserT UserT { get; set; }
    }
}
